name: ci

on:
  workflow_dispatch:
  
jobs:
  android:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android:v13.0
    steps:
      - uses: actions/checkout@v4
      - name: Configure android arm64
        # see build options you can use in https://developer.android.com/ndk/guides/cmake
        run: |
          mkdir build
          cd build
          "$ANDROID_HOME/cmake/3.22.1/bin/cmake" "-DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk/26.0.10792818/build/cmake/android.toolchain.cmake" -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DQJS_BUILD_LIBC=ON ..
      - name: Build android arm64
        run: |
          "$ANDROID_HOME/cmake/3.22.1/bin/cmake" --build build --target qjs_exe
          ls -lh build
      
      # 把产物放到单独的目录方便上传
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          # 根据实际产物名/路径调整
          cp build/libqjs.a artifacts/
          cp build/qjs artifacts/

      # 上传到 GitHub Actions 的 artifact 存储
      - name: Upload compiled library
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-libqjs
          path: artifacts
          retention-days: 7          # 按需保留天数
      
